include:
  - docker-compose.yml
  - external-proxy/opencloud.yml

services:
  opencloud:
    networks:
      opencloud-net:
      dokploy-network:
      
volumes:
  opencloud-config:
  opencloud-data:

networks:
  opencloud-net:
  dokploy-network:
    external: true
