include:
    - docker-compose.yml
    - external-proxy/opencloud.yml
    - idm/ldap-keycloak.yml

services:
    opencloud:
        networks:
            opencloud-net:

volumes:
    opencloud-config:
    opencloud-data:
    keycloak_postgres_data:
    ldap-certs:
    ldap-data:

networks:
    opencloud-net:
